// ISO 3166-1 alpha-2 codes mapped to a single representative IANA timezone.
// Large multi-zone countries (US, RU, CA, AU, BR) are pinned to one
// well-known zone -- acceptable for this app's primary market (Africa,
// which is effectively single-zone-per-country with no DST).
export const COUNTRIES: ReadonlyArray<{ code: string; name: string; timezone: string }> = [
  { code: "DZ", name: "Algeria", timezone: "Africa/Algiers" },
  { code: "AO", name: "Angola", timezone: "Africa/Luanda" },
  { code: "BJ", name: "Benin", timezone: "Africa/Porto-Novo" },
  { code: "BW", name: "Botswana", timezone: "Africa/Gaborone" },
  { code: "BF", name: "Burkina Faso", timezone: "Africa/Ouagadougou" },
  { code: "BI", name: "Burundi", timezone: "Africa/Bujumbura" },
  { code: "CM", name: "Cameroon", timezone: "Africa/Douala" },
  { code: "CV", name: "Cape Verde", timezone: "Atlantic/Cape_Verde" },
  { code: "CF", name: "Central African Republic", timezone: "Africa/Bangui" },
  { code: "TD", name: "Chad", timezone: "Africa/Ndjamena" },
  { code: "KM", name: "Comoros", timezone: "Indian/Comoro" },
  { code: "CG", name: "Congo (Republic)", timezone: "Africa/Brazzaville" },
  { code: "CD", name: "Congo (DRC)", timezone: "Africa/Kinshasa" },
  { code: "CI", name: "Côte d'Ivoire", timezone: "Africa/Abidjan" },
  { code: "DJ", name: "Djibouti", timezone: "Africa/Djibouti" },
  { code: "EG", name: "Egypt", timezone: "Africa/Cairo" },
  { code: "GQ", name: "Equatorial Guinea", timezone: "Africa/Malabo" },
  { code: "ER", name: "Eritrea", timezone: "Africa/Asmara" },
  { code: "SZ", name: "Eswatini", timezone: "Africa/Mbabane" },
  { code: "ET", name: "Ethiopia", timezone: "Africa/Addis_Ababa" },
  { code: "GA", name: "Gabon", timezone: "Africa/Libreville" },
  { code: "GM", name: "Gambia", timezone: "Africa/Banjul" },
  { code: "GH", name: "Ghana", timezone: "Africa/Accra" },
  { code: "GN", name: "Guinea", timezone: "Africa/Conakry" },
  { code: "GW", name: "Guinea-Bissau", timezone: "Africa/Bissau" },
  { code: "KE", name: "Kenya", timezone: "Africa/Nairobi" },
  { code: "LS", name: "Lesotho", timezone: "Africa/Maseru" },
  { code: "LR", name: "Liberia", timezone: "Africa/Monrovia" },
  { code: "LY", name: "Libya", timezone: "Africa/Tripoli" },
  { code: "MG", name: "Madagascar", timezone: "Indian/Antananarivo" },
  { code: "MW", name: "Malawi", timezone: "Africa/Blantyre" },
  { code: "ML", name: "Mali", timezone: "Africa/Bamako" },
  { code: "MR", name: "Mauritania", timezone: "Africa/Nouakchott" },
  { code: "MU", name: "Mauritius", timezone: "Indian/Mauritius" },
  { code: "MA", name: "Morocco", timezone: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", timezone: "Africa/Maputo" },
  { code: "NA", name: "Namibia", timezone: "Africa/Windhoek" },
  { code: "NE", name: "Niger", timezone: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", timezone: "Africa/Lagos" },
  { code: "RW", name: "Rwanda", timezone: "Africa/Kigali" },
  { code: "ST", name: "São Tomé and Príncipe", timezone: "Africa/Sao_Tome" },
  { code: "SN", name: "Senegal", timezone: "Africa/Dakar" },
  { code: "SC", name: "Seychelles", timezone: "Indian/Mahe" },
  { code: "SL", name: "Sierra Leone", timezone: "Africa/Freetown" },
  { code: "SO", name: "Somalia", timezone: "Africa/Mogadishu" },
  { code: "ZA", name: "South Africa", timezone: "Africa/Johannesburg" },
  { code: "SS", name: "South Sudan", timezone: "Africa/Juba" },
  { code: "SD", name: "Sudan", timezone: "Africa/Khartoum" },
  { code: "TZ", name: "Tanzania", timezone: "Africa/Dar_es_Salaam" },
  { code: "TG", name: "Togo", timezone: "Africa/Lome" },
  { code: "TN", name: "Tunisia", timezone: "Africa/Tunis" },
  { code: "UG", name: "Uganda", timezone: "Africa/Kampala" },
  { code: "ZM", name: "Zambia", timezone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", timezone: "Africa/Harare" },

  { code: "AL", name: "Albania", timezone: "Europe/Tirane" },
  { code: "AD", name: "Andorra", timezone: "Europe/Andorra" },
  { code: "AT", name: "Austria", timezone: "Europe/Vienna" },
  { code: "BY", name: "Belarus", timezone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", timezone: "Europe/Brussels" },
  { code: "BA", name: "Bosnia and Herzegovina", timezone: "Europe/Sarajevo" },
  { code: "BG", name: "Bulgaria", timezone: "Europe/Sofia" },
  { code: "HR", name: "Croatia", timezone: "Europe/Zagreb" },
  { code: "CY", name: "Cyprus", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czechia", timezone: "Europe/Prague" },
  { code: "DK", name: "Denmark", timezone: "Europe/Copenhagen" },
  { code: "EE", name: "Estonia", timezone: "Europe/Tallinn" },
  { code: "FI", name: "Finland", timezone: "Europe/Helsinki" },
  { code: "FR", name: "France", timezone: "Europe/Paris" },
  { code: "DE", name: "Germany", timezone: "Europe/Berlin" },
  { code: "GR", name: "Greece", timezone: "Europe/Athens" },
  { code: "HU", name: "Hungary", timezone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", timezone: "Atlantic/Reykjavik" },
  { code: "IE", name: "Ireland", timezone: "Europe/Dublin" },
  { code: "IT", name: "Italy", timezone: "Europe/Rome" },
  { code: "XK", name: "Kosovo", timezone: "Europe/Belgrade" },
  { code: "LV", name: "Latvia", timezone: "Europe/Riga" },
  { code: "LI", name: "Liechtenstein", timezone: "Europe/Vaduz" },
  { code: "LT", name: "Lithuania", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", timezone: "Europe/Luxembourg" },
  { code: "MT", name: "Malta", timezone: "Europe/Malta" },
  { code: "MD", name: "Moldova", timezone: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", timezone: "Europe/Monaco" },
  { code: "ME", name: "Montenegro", timezone: "Europe/Podgorica" },
  { code: "NL", name: "Netherlands", timezone: "Europe/Amsterdam" },
  { code: "MK", name: "North Macedonia", timezone: "Europe/Skopje" },
  { code: "NO", name: "Norway", timezone: "Europe/Oslo" },
  { code: "PL", name: "Poland", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", timezone: "Europe/Lisbon" },
  { code: "RO", name: "Romania", timezone: "Europe/Bucharest" },
  { code: "RU", name: "Russia", timezone: "Europe/Moscow" },
  { code: "SM", name: "San Marino", timezone: "Europe/San_Marino" },
  { code: "RS", name: "Serbia", timezone: "Europe/Belgrade" },
  { code: "SK", name: "Slovakia", timezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", timezone: "Europe/Ljubljana" },
  { code: "ES", name: "Spain", timezone: "Europe/Madrid" },
  { code: "SE", name: "Sweden", timezone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", timezone: "Europe/Zurich" },
  { code: "UA", name: "Ukraine", timezone: "Europe/Kyiv" },
  { code: "GB", name: "United Kingdom", timezone: "Europe/London" },
  { code: "VA", name: "Vatican City", timezone: "Europe/Vatican" },

  { code: "AF", name: "Afghanistan", timezone: "Asia/Kabul" },
  { code: "AM", name: "Armenia", timezone: "Asia/Yerevan" },
  { code: "AZ", name: "Azerbaijan", timezone: "Asia/Baku" },
  { code: "BH", name: "Bahrain", timezone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", timezone: "Asia/Dhaka" },
  { code: "BT", name: "Bhutan", timezone: "Asia/Thimphu" },
  { code: "BN", name: "Brunei", timezone: "Asia/Brunei" },
  { code: "KH", name: "Cambodia", timezone: "Asia/Phnom_Penh" },
  { code: "CN", name: "China", timezone: "Asia/Shanghai" },
  { code: "GE", name: "Georgia", timezone: "Asia/Tbilisi" },
  { code: "IN", name: "India", timezone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", timezone: "Asia/Jakarta" },
  { code: "IR", name: "Iran", timezone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", timezone: "Asia/Baghdad" },
  { code: "IL", name: "Israel", timezone: "Asia/Jerusalem" },
  { code: "JP", name: "Japan", timezone: "Asia/Tokyo" },
  { code: "JO", name: "Jordan", timezone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", timezone: "Asia/Almaty" },
  { code: "KW", name: "Kuwait", timezone: "Asia/Kuwait" },
  { code: "KG", name: "Kyrgyzstan", timezone: "Asia/Bishkek" },
  { code: "LA", name: "Laos", timezone: "Asia/Vientiane" },
  { code: "LB", name: "Lebanon", timezone: "Asia/Beirut" },
  { code: "MY", name: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", timezone: "Indian/Maldives" },
  { code: "MN", name: "Mongolia", timezone: "Asia/Ulaanbaatar" },
  { code: "MM", name: "Myanmar", timezone: "Asia/Yangon" },
  { code: "NP", name: "Nepal", timezone: "Asia/Kathmandu" },
  { code: "KP", name: "North Korea", timezone: "Asia/Pyongyang" },
  { code: "OM", name: "Oman", timezone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", timezone: "Asia/Karachi" },
  { code: "PS", name: "Palestine", timezone: "Asia/Gaza" },
  { code: "PH", name: "Philippines", timezone: "Asia/Manila" },
  { code: "QA", name: "Qatar", timezone: "Asia/Qatar" },
  { code: "SA", name: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { code: "SG", name: "Singapore", timezone: "Asia/Singapore" },
  { code: "KR", name: "South Korea", timezone: "Asia/Seoul" },
  { code: "LK", name: "Sri Lanka", timezone: "Asia/Colombo" },
  { code: "SY", name: "Syria", timezone: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", timezone: "Asia/Taipei" },
  { code: "TJ", name: "Tajikistan", timezone: "Asia/Dushanbe" },
  { code: "TH", name: "Thailand", timezone: "Asia/Bangkok" },
  { code: "TL", name: "Timor-Leste", timezone: "Asia/Dili" },
  { code: "TR", name: "Turkey", timezone: "Europe/Istanbul" },
  { code: "TM", name: "Turkmenistan", timezone: "Asia/Ashgabat" },
  { code: "AE", name: "United Arab Emirates", timezone: "Asia/Dubai" },
  { code: "UZ", name: "Uzbekistan", timezone: "Asia/Tashkent" },
  { code: "VN", name: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { code: "YE", name: "Yemen", timezone: "Asia/Aden" },

  { code: "AG", name: "Antigua and Barbuda", timezone: "America/Antigua" },
  { code: "AR", name: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { code: "BS", name: "Bahamas", timezone: "America/Nassau" },
  { code: "BB", name: "Barbados", timezone: "America/Barbados" },
  { code: "BZ", name: "Belize", timezone: "America/Belize" },
  { code: "BO", name: "Bolivia", timezone: "America/La_Paz" },
  { code: "BR", name: "Brazil", timezone: "America/Sao_Paulo" },
  { code: "CA", name: "Canada", timezone: "America/Toronto" },
  { code: "CL", name: "Chile", timezone: "America/Santiago" },
  { code: "CO", name: "Colombia", timezone: "America/Bogota" },
  { code: "CR", name: "Costa Rica", timezone: "America/Costa_Rica" },
  { code: "CU", name: "Cuba", timezone: "America/Havana" },
  { code: "DM", name: "Dominica", timezone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", timezone: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", timezone: "America/Guayaquil" },
  { code: "SV", name: "El Salvador", timezone: "America/El_Salvador" },
  { code: "GD", name: "Grenada", timezone: "America/Grenada" },
  { code: "GT", name: "Guatemala", timezone: "America/Guatemala" },
  { code: "GY", name: "Guyana", timezone: "America/Guyana" },
  { code: "HT", name: "Haiti", timezone: "America/Port-au-Prince" },
  { code: "HN", name: "Honduras", timezone: "America/Tegucigalpa" },
  { code: "JM", name: "Jamaica", timezone: "America/Jamaica" },
  { code: "MX", name: "Mexico", timezone: "America/Mexico_City" },
  { code: "NI", name: "Nicaragua", timezone: "America/Managua" },
  { code: "PA", name: "Panama", timezone: "America/Panama" },
  { code: "PY", name: "Paraguay", timezone: "America/Asuncion" },
  { code: "PE", name: "Peru", timezone: "America/Lima" },
  { code: "KN", name: "Saint Kitts and Nevis", timezone: "America/St_Kitts" },
  { code: "LC", name: "Saint Lucia", timezone: "America/St_Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines", timezone: "America/St_Vincent" },
  { code: "SR", name: "Suriname", timezone: "America/Paramaribo" },
  { code: "TT", name: "Trinidad and Tobago", timezone: "America/Port_of_Spain" },
  { code: "US", name: "United States", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", timezone: "America/Montevideo" },
  { code: "VE", name: "Venezuela", timezone: "America/Caracas" },

  { code: "AU", name: "Australia", timezone: "Australia/Sydney" },
  { code: "FJ", name: "Fiji", timezone: "Pacific/Fiji" },
  { code: "KI", name: "Kiribati", timezone: "Pacific/Tarawa" },
  { code: "MH", name: "Marshall Islands", timezone: "Pacific/Majuro" },
  { code: "FM", name: "Micronesia", timezone: "Pacific/Chuuk" },
  { code: "NR", name: "Nauru", timezone: "Pacific/Nauru" },
  { code: "NZ", name: "New Zealand", timezone: "Pacific/Auckland" },
  { code: "PW", name: "Palau", timezone: "Pacific/Palau" },
  { code: "PG", name: "Papua New Guinea", timezone: "Pacific/Port_Moresby" },
  { code: "WS", name: "Samoa", timezone: "Pacific/Apia" },
  { code: "SB", name: "Solomon Islands", timezone: "Pacific/Guadalcanal" },
  { code: "TO", name: "Tonga", timezone: "Pacific/Tongatapu" },
  { code: "TV", name: "Tuvalu", timezone: "Pacific/Funafuti" },
  { code: "VU", name: "Vanuatu", timezone: "Pacific/Efate" },
];

export const COUNTRY_CODES: string[] = COUNTRIES.map((entry) => entry.code);

export function getTimezoneForCountry(code: string): string {
  return COUNTRIES.find((entry) => entry.code === code.toUpperCase())?.timezone ?? "UTC";
}
